from dataclasses import dataclass, field


@dataclass
class RuleContext:
    """
    Shared object passed to every rule.
    """

    resources: list

    issues: list = field(default_factory=list)

    logs: list = field(default_factory=list)

    metadata: dict = field(default_factory=dict)

    def report(self, **issue):
        """
        Add an issue from a rule.

        Example:
            ctx.report(
                id="POD-001",
                severity="HIGH",
                resource_type="Pod",
                resource_name="nginx",
                namespace="default",
                title="CrashLoopBackOff",
                description="Pod is crashing repeatedly.",
                evidence={},
                recommendation="Check container logs."
            )
        """
        self.issues.append(issue)

    def log(self, level: str, message: str):
        """
        Add a log message.
        """
        self.logs.append(
            {
                "level": level.upper(),
                "message": message,
            }
        )

    def set_metadata(self, key, value):
        """
        Store metadata generated by rules.
        """
        self.metadata[key] = value

    @property
    def result(self):
        """
        Backward compatibility.
        """
        return self